# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9da5b297aec6b1065abca2973a9a1a86995c14c6802ee5981c8cb72855917ae497d84a1ba5c6bc7ff3baab2d3d05e1bbc1cd474d4166b9e8551ca68596b1933

test:
  secret_key_base: e33ce54fd32c06a113bac05dc9611a7c42653fd0f0d1246332d9b9944e0ae2d2ad6c909ea3def5fbbbaebee4b96af384f92dfe939f48cb5dce5bc1f56c22943f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
